version: "3"
services:
    client:
      restart: always
      build: ./client
      ports:
        - "80:80"
    server:
      restart: always
      build: ./server
      ports:
        - "3000:3000"
      links:
        - mongo
    mongo:
      image: mongo
      volumes:
        - ./data:/data/db
      ports:
        - "27017:27017"