FROM node:8

# Create app directory
WORKDIR /usr/src/app/server

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
ADD ./server/package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
ADD ./.env ./../
ADD ./server ./
ADD ./both ./../both

CMD [ "npm", "start" ]
